import gen_curriculum as g
S = g.S

# ============================ REEF & COASTAL FISHES ============================
S("fish-clownfish","Clownfish","damselfish","organisms","reef","plankton","It shelters unharmed among the stinging tentacles of sea anemones, protected by a layer of special mucus, in a famous mutualism.")
S("fish-mandarinfish","Mandarinfish","dragonet","organisms","reef","inverts","Its dazzling blue, orange and green pattern comes from true blue pigment cells, which are extremely rare in the animal kingdom.")
S("fish-parrotfish","Parrotfish","reef fish","organisms","reef","algae","Its fused beak-like teeth scrape algae off coral, and it grinds up rock that it later excretes as fine white sand.")
S("fish-wrasse","Cleaner wrasse","wrasse","organisms","reef","parasites","It runs a 'cleaning station,' picking parasites and dead skin from much larger fish that wait their turn to be groomed.")
S("fish-angelfish","Queen angelfish","angelfish","organisms","reef","sponges","Bright blue and yellow as an adult, it changes color dramatically as it grows from a striped juvenile.")
S("fish-butterflyfish","Butterflyfish","butterflyfish","organisms","reef","coral","Many species mate for life and swim in pairs, and a dark eyespot near the tail can fool predators about which end is the head.")
S("fish-surgeonfish","Surgeonfish","surgeonfish","organisms","reef","algae","It is named for a sharp, scalpel-like spine near its tail that it can flick out in self-defense.")
S("fish-tang","Blue tang","surgeonfish","organisms","reef","algae","A vivid blue reef grazer with a yellow tail, it can play dead when threatened by lying motionless on its side.")
S("fish-triggerfish","Triggerfish","triggerfish","organisms","reef","inverts","It can lock its first dorsal spine upright with a second 'trigger' spine, wedging itself into a crevice so predators cannot pull it out.")
S("fish-pufferfish","Pufferfish","pufferfish","organisms","reef","inverts","When threatened it gulps water to swell into a spiny ball, and many species carry a potent toxin called tetrodotoxin.")
S("fish-porcupinefish","Porcupinefish","pufferfish","organisms","reef","inverts","Close relative of the puffer, it is covered in long spines that stand out stiffly when it inflates.")
S("fish-boxfish","Boxfish","boxfish","organisms","reef","inverts","Its body is encased in a rigid box of fused bony plates, so only its fins, eyes and mouth can move.")
S("fish-lionfish","Lionfish","scorpionfish","organisms","reef","fish","Its fan of venomous spines deters predators; native to the Indo-Pacific, it has become a damaging invader in the Atlantic.")
S("fish-stonefish","Stonefish","scorpionfish","organisms","reef","fish","Camouflaged as an algae-covered rock, it is considered the most venomous fish in the world.")
S("fish-scorpionfish","Scorpionfish","scorpionfish","organisms","reef","fish","A master of camouflage with venomous spines, it ambushes prey by sitting motionless and blending into the reef.")
S("fish-frogfish","Frogfish","anglerfish (shallow)","organisms","reef","fish","It walks on leg-like fins and dangles a tiny built-in lure to draw prey within reach of its lightning-fast gulp.")
S("fish-grouper","Goliath grouper","grouper","organisms","reef","fishsquid","One of the largest reef fish, it can grow to hundreds of kilograms and makes a deep booming sound to warn off intruders.")
S("fish-snapper","Red snapper","snapper","organisms","reef","fish","A prized food fish, it gathers in large spawning groups and can live for over fifty years.")
S("fish-grunt","Grunt","grunt","organisms","reef","inverts","It makes a grunting sound by grinding its throat teeth, amplified by its swim bladder.")
S("fish-goatfish","Goatfish","goatfish","organisms","sand","inverts","It uses a pair of whisker-like barbels under its chin to taste and probe the sand for buried prey.")
S("fish-moorishidol","Moorish idol","reef fish","organisms","reef","sponges","Famous for its bold black, white and yellow bands and a long trailing dorsal filament.")
S("fish-damselfish","Damselfish","damselfish","organisms","reef","algae","Small but fearless, it farms and fiercely defends patches of algae, chasing away fish many times its size.")
S("fish-anthias","Anthias","reef fish","organisms","reef","plankton","These shimmering fish swarm above reefs by the thousands, and dominant females can change sex to become males.")
S("fish-cardinalfish","Cardinalfish","cardinalfish","organisms","reef","plankton","A mouthbrooder: the male carries the developing eggs in his mouth until they hatch.")
S("fish-goby","Goby","goby","organisms","reef","inverts","Among the smallest vertebrates, some gobies share a burrow with a shrimp, trading lookout duty for shelter.")
S("fish-blenny","Blenny","blenny","organisms","rocky","algae","A small, big-eyed fish that perches in holes and crevices, darting out to feed and back to safety.")
S("fish-hawkfish","Hawkfish","hawkfish","organisms","reef","inverts","It perches motionless on coral like a hawk on a branch, then pounces on passing prey.")
S("fish-pipefish","Pipefish","pipefish","organisms","seagrass","plankton","A stretched-out relative of the seahorse; like seahorses, the male carries the eggs.")
S("fish-seahorse","Seahorse","seahorse","organisms","seagrass","plankton","It is one of the few animals where the male becomes pregnant, brooding eggs in a belly pouch until they hatch.")
S("fish-razorfish","Razorfish (shrimpfish)","shrimpfish","organisms","seagrass","plankton","It swims head-down in synchronized groups, hiding among sea urchin spines and seagrass.")
S("fish-filefish","Filefish","filefish","organisms","reef","algae","Named for its rough, sandpapery skin, it can change color to blend with corals and weeds.")
S("fish-rabbitfish","Rabbitfish","rabbitfish","organisms","reef","algae","A reef grazer with venomous fin spines and a small, rabbit-like mouth for nibbling algae.")
S("fish-sweetlips","Sweetlips","grunt relative","organisms","reef","inverts","Juveniles wiggle dramatically to mimic toxic flatworms, gaining protection until they grow up.")
S("fish-fusilier","Fusilier","reef fish","organisms","reef","plankton","Streamlined and fast, it forms huge schools that sweep over reefs feeding on drifting plankton.")
S("fish-soldierfish","Soldierfish","squirrelfish relative","organisms","reef","plankton","A red, big-eyed fish that hides in reef caves by day and emerges at night to feed.")
S("fish-squirrelfish","Squirrelfish","squirrelfish","organisms","reef","inverts","Its large eyes suit a nocturnal life, and it can make clicking sounds to communicate.")
S("fish-bigeye","Bigeye","bigeye","organisms","reef","plankton","Enormous eyes gather faint light for hunting plankton at dusk and through the night.")
S("fish-batfish","Batfish","spadefish","organisms","reef","omni","Tall and disc-shaped as an adult, its long-finned juveniles drift and sway to mimic dead leaves.")
S("fish-jackfish","Giant trevally","jack","organisms","coast","fish","A powerful, fast predator that hunts in packs and has even been filmed leaping to snatch seabirds.")
S("fish-pompano","Pompano","jack","organisms","coast","inverts","A swift, deep-bodied jack of sandy coasts, prized as a food fish.")
S("fish-remora","Remora","suckerfish","organisms","open","detritus","It hitchhikes on sharks, turtles and whales using a flat sucker on its head, eating scraps and parasites.")
S("fish-cobia","Cobia","cobia","organisms","coast","crabs","Often mistaken for a shark, it shadows large animals and shipwrecks in search of crabs and fish.")
S("fish-mullet","Mullet","mullet","organisms","coast","detritus","It feeds on algae and detritus in shallows and is famous for leaping clear of the water.")
S("fish-mudskipper","Mudskipper","goby (amphibious)","organisms","mang","inverts","It can breathe air and 'walk' across mudflats on its fins, spending much of low tide out of the water.")
S("fish-archerfish","Archerfish","archerfish","organisms","mang","inverts","It shoots down insects above the water by spitting a precise jet of water from its mouth.")
S("fish-flounder","Flounder","flatfish","organisms","sand","fish","As it grows, one eye migrates to join the other so it can lie flat on the seabed, both eyes facing up.")
S("fish-halibut","Halibut","flatfish","organisms","shelf","fish","A giant flatfish of cold seas, it can grow over two meters long and lies camouflaged on the bottom.")
S("fish-sole","Sole","flatfish","organisms","sand","worms","A small flatfish that buries in sand and feeds at night on worms and tiny invertebrates.")
S("fish-stargazer","Stargazer","stargazer","organisms","sand","fish","It buries in sand with only its upward-facing eyes and mouth showing, ambushing prey from below; some can even deliver an electric shock.")
S("fish-toadfish","Toadfish","toadfish","organisms","sand","inverts","The male hums loudly using its swim bladder to attract females, one of the loudest fish sounds.")
S("fish-flyingfish","Flying fish","flyingfish","organisms","open","plankton","It escapes predators by gliding above the surface on wing-like fins, sometimes for hundreds of meters.")
S("fish-needlefish","Needlefish","needlefish","organisms","coast","fish","A slender surface hunter with a long beak of sharp teeth that can skitter across the water at speed.")
S("fish-halfbeak","Halfbeak","halfbeak","organisms","coast","plankton","Named for its single elongated lower jaw, it skims plankton just beneath the surface.")
S("fish-tarpon","Tarpon","tarpon","organisms","coast","fish","A large silver gamefish that can gulp air at the surface, letting it survive in low-oxygen water.")
S("fish-snook","Snook","snook","organisms","mang","fish","An ambush predator of mangroves and inlets, marked by a bold black line along its side.")

# ============================ PELAGIC & OPEN-OCEAN FISHES ============================
S("fish-tuna-bluefin","Bluefin tuna","tuna","organisms","open","fishsquid","One of the fastest, warmest-blooded fish, it keeps its muscles above water temperature to power long, high-speed migrations across oceans.")
S("fish-tuna-yellowfin","Yellowfin tuna","tuna","organisms","open","fishsquid","A sleek, powerful predator that often swims with dolphins and can sprint after fast prey.")
S("fish-mackerel","Atlantic mackerel","mackerel","organisms","open","plankton","It forms enormous fast-moving schools and is a key food fish for larger predators.")
S("fish-wahoo","Wahoo","mackerel relative","organisms","open","fish","Among the fastest fish in the sea, it strikes prey in short, blistering bursts.")
S("fish-kingmackerel","King mackerel","mackerel","organisms","coast","fish","A swift coastal predator that migrates in schools and is a favorite of sport anglers.")
S("fish-bonito","Bonito","tuna relative","organisms","open","fish","A small, striped tuna relative that hunts in fast schools near the surface.")
S("fish-mahimahi","Mahi-mahi","dolphinfish","organisms","open","fish","Brilliantly colored and fast-growing, it gathers under floating debris and fades to silver soon after being caught.")
S("fish-marlin-blue","Blue marlin","billfish","organisms","open","fishsquid","It uses its long spear-like bill to stun prey and is among the largest and fastest of all bony fish.")
S("fish-sailfish","Sailfish","billfish","organisms","open","fish","Often called the fastest fish, it raises a huge sail-like fin to herd baitfish before striking.")
S("fish-swordfish","Swordfish","billfish","organisms","open","squid","It has special tissue that warms its eyes and brain, sharpening its senses as it hunts in cold, deep water.")
S("fish-bluefish","Bluefish","bluefish","organisms","coast","fish","A ferocious schooling predator known for feeding frenzies that churn the water.")
S("fish-jackmackerel","Jack mackerel","jack","organisms","open","plankton","It forms vast offshore schools that support major fisheries and many predators.")
S("fish-opah","Opah (moonfish)","opah","organisms","open","squid","A round, deep-living fish, it is one of the few known to be fully warm-blooded, heating its whole body.")
S("fish-sunfish-mola","Ocean sunfish (mola)","sunfish","organisms","open","jellies","The heaviest bony fish in the world, this strange flattened giant basks at the surface and feeds largely on jellyfish.")
S("fish-oarfish","Oarfish","oarfish","organisms","deep","krill","The longest bony fish, this ribbon-like deep-sea giant likely inspired old tales of sea serpents.")
S("fish-herring","Atlantic herring","herring","organisms","open","plankton","It schools in the millions and is a cornerstone food fish linking plankton to seabirds, whales and people.")
S("fish-sardine","Sardine","herring relative","organisms","coast","plankton","Its huge migrating schools, like South Africa's sardine run, draw predators from sharks to dolphins to gannets.")
S("fish-anchovy","Anchovy","anchovy","organisms","coast","plankton","Tiny but vital, dense anchovy schools fuel some of the world's largest fisheries and feed countless predators.")
S("fish-menhaden","Menhaden","herring relative","organisms","coast","filter","A filter feeder that strains plankton, it is so important as food and fertilizer it has been called 'the most important fish in the sea.'")
S("fish-capelin","Capelin","smelt","organisms","polar","plankton","A small cold-water fish whose mass spawning feeds whales, seabirds and cod in the far north.")
S("fish-barracuda","Great barracuda","barracuda","organisms","reef","fish","A fast, fang-toothed ambush predator that relies on bursts of speed and is drawn to shiny objects.")

# ============================ DEEP-SEA FISHES ============================
S("fish-anglerfish-deep","Deep-sea anglerfish","anglerfish","organisms","deep","fish","It dangles a glowing, bacteria-lit lure to draw prey out of the darkness; in some species the tiny male fuses permanently to the female.")
S("fish-viperfish","Viperfish","dragonfish relative","organisms","deep","fishsquid","Its fangs are so long they do not fit inside its mouth, and a glowing lure helps tempt prey close.")
S("fish-dragonfish","Black dragonfish","dragonfish","organisms","deep","fish","It produces and even sees red light, an invisible 'searchlight' that most deep-sea animals cannot detect.")
S("fish-gulper","Gulper eel (pelican eel)","eel","organisms","deep","fishsquid","Its enormous, balloon-like mouth can engulf prey larger than itself in the food-poor deep.")
S("fish-hatchetfish","Hatchetfish","hatchetfish","organisms","twilight","plankton","Light organs on its belly match the dim glow from above, erasing its silhouette from predators below.")
S("fish-lanternfish","Lanternfish","lanternfish","organisms","twilight","zoopl","Rows of light organs and nightly migrations to the surface make these among the most abundant fish on Earth.")
S("fish-bristlemouth","Bristlemouth","bristlemouth","organisms","twilight","plankton","Tiny and glowing, bristlemouths may be the most numerous vertebrates on the planet.")
S("fish-fangtooth","Fangtooth","fangtooth","organisms","deep","fishsquid","Despite a fearsome look and the largest teeth for its size of any fish, it is only the size of a fist.")
S("fish-tripod","Tripodfish","deep-sea fish","organisms","deep","plankton","It stands on three long, stiff fin rays like a tripod, facing the current to catch drifting food.")
S("fish-grenadier","Grenadier (rattail)","grenadier","organisms","deep","detritus","A long-tailed, big-headed scavenger that is among the most common fish on the deep seafloor.")
S("fish-blobfish","Blobfish","fathead sculpin","organisms","deep","inverts","Gelatinous and nearly weightless, it drifts just above the seabed; its famous 'blobby' look only appears once it is hauled to the surface.")
S("fish-coffinfish","Coffinfish","deep-sea anglerfish","organisms","deep","fish","A small deep-sea angler that can gulp and hold water, puffing up and slowing its breathing to save energy.")
S("fish-lizardfish","Deep-sea lizardfish","lizardfish","organisms","deep","fish","A patient bottom ambusher with a toothy grin that waits motionless for prey to pass.")
S("fish-snailfish-deep","Hadal snailfish","snailfish","organisms","deep","crabs","Soft and gelatinous, it lives deeper than 8,000 m, the deepest fish ever recorded.")
S("fish-cusk-eel","Cusk-eel","cusk-eel","organisms","deep","inverts","Some cusk-eels hold the record for the deepest-living fish caught from the very bottom of ocean trenches.")
S("fish-coelacanth","Coelacanth","lobe-finned fish","organisms","deep","fishsquid","A 'living fossil' once thought extinct for millions of years, it has fleshy, limb-like fins and was rediscovered alive in 1938.")
S("fish-chimaera","Chimaera (ratfish)","cartilaginous fish","organisms","deep","crabs","A deep-dwelling relative of sharks with a venomous spine and a soft, tapering body.")

# ============================ EELS & ODD FISHES ============================
S("fish-moray","Moray eel","eel","organisms","reef","fishsquid","It has a second set of jaws in its throat that shoot forward to grab and pull prey down, and it gapes to breathe, not to threaten.")
S("fish-gardeneel","Garden eel","eel","organisms","sand","plankton","Colonies poke from the sand swaying in the current to grab plankton, retreating into their burrows when threatened.")
S("fish-conger","Conger eel","eel","organisms","rocky","fishsquid","A large nocturnal eel that shelters in rocky holds and wrecks, emerging at night to hunt.")
S("fish-electriceel","Electric eel","knifefish (not a true eel)","organisms","mang","fish","Despite the name it is not a true eel; it can deliver a powerful electric shock to stun prey and defend itself.")
S("fish-freshwater-eel","American eel","eel","organisms","mang","inverts","It hatches far out in the Sargasso Sea, migrates into rivers to grow, then returns to the open ocean to spawn.")
S("fish-lamprey","Sea lamprey","jawless fish","organisms","coast","blood","One of the oldest fish lineages, it has no jaws; instead a round, toothed sucker latches onto other fish.")
S("fish-hagfish","Hagfish","jawless fish","organisms","deep","detritus","When attacked it instantly unleashes clouds of slime that clog a predator's gills, and it can tie itself in a knot to escape.")
S("fish-sturgeon","Sturgeon","sturgeon","organisms","coast","worms","An ancient armored fish that can live over a century and is prized (and threatened) for its eggs, sold as caviar.")
S("fish-seadragon","Leafy seadragon","seahorse relative","organisms","kelp","plankton","Adorned with leaf-shaped flaps, it drifts through seaweed in near-perfect camouflage; like seahorses, the male carries the eggs.")

# ============================ SHARKS ============================
S("shark-greatwhite","Great white shark","shark","organisms","coast","seals","A warm-bodied apex predator, it can launch fully out of the water to ambush seals from below.")
S("shark-tiger","Tiger shark","shark","organisms","tropic","omni","Nicknamed the ocean's garbage can, it eats almost anything and bears dark stripes that fade with age.")
S("shark-bull","Bull shark","shark","organisms","coast","fish","Uniquely tolerant of fresh water, it swims far up rivers and into lakes well away from the sea.")
S("shark-hammerhead","Great hammerhead","shark","organisms","tropic","ray","Its wide, flat head spreads its sensory organs for a better sweep, and it uses the 'hammer' to pin stingrays.")
S("shark-mako","Shortfin mako","shark","organisms","open","fishsquid","The fastest shark, it is warm-bodied and can leap high out of the water chasing fast prey.")
S("shark-blue","Blue shark","shark","organisms","open","squid","Slender and far-roaming, it makes some of the longest migrations of any shark across entire oceans.")
S("shark-whaleshark","Whale shark","shark","organisms","tropic","plankton","The largest fish in the world, this gentle giant cruises slowly, filtering plankton from huge mouthfuls of water.")
S("shark-basking","Basking shark","shark","organisms","coast","plankton","The second-largest fish, it filters plankton with its cavernous mouth while swimming near the surface.")
S("shark-megamouth","Megamouth shark","shark","organisms","deep","plankton","A rare deep-water filter feeder, it was unknown to science until 1976.")
S("shark-thresher","Thresher shark","shark","organisms","open","fish","It stuns schooling fish by whipping its enormously long tail like a weapon.")
S("shark-nurse","Nurse shark","shark","organisms","reef","crabs","A slow, docile bottom-dweller, it rests by day and uses suction to slurp prey from crevices at night.")
S("shark-lemon","Lemon shark","shark","organisms","mang","fish","Yellow-tinged for camouflage over sand, its pups grow up in the shelter of mangrove nurseries.")
S("shark-reef-blacktip","Blacktip reef shark","shark","organisms","reef","fish","A common, shy reef shark recognized by the black tips on its fins, often seen in shallow lagoons.")
S("shark-reef-whitetip","Whitetip reef shark","shark","organisms","reef","fish","It rests in caves by day, then hunts cooperatively at night, wriggling into crevices after prey.")
S("shark-sandtiger","Sand tiger shark","shark","organisms","coast","fish","Fierce-looking but fairly placid, it gulps air at the surface to hover motionless in the water.")
S("shark-goblin","Goblin shark","shark","organisms","deep","fish","A rare deep-sea 'living fossil' whose jaws shoot far forward to snatch prey, then snap back.")
S("shark-frilled","Frilled shark","shark","organisms","deep","squid","An eel-like deep-water shark with frilly gills and rows of needle teeth, little changed for millions of years.")
S("shark-cookiecutter","Cookiecutter shark","shark","organisms","deep","fish","Small but bold, it gouges round plugs of flesh from animals far larger than itself, including whales.")
S("shark-greenland","Greenland shark","shark","organisms","polar","seals","A slow Arctic giant, it is the longest-lived vertebrate known, with individuals estimated to be centuries old.")
S("shark-wobbegong","Wobbegong","carpet shark","organisms","reef","fish","A flattened, frilled bottom shark whose camouflage makes it nearly invisible as it ambushes prey.")
S("shark-angel","Angelshark","shark","organisms","sand","fish","Flat and ray-like, it buries in sand and bursts upward to seize fish swimming overhead.")
S("shark-saw","Sawshark","shark","organisms","sand","crabs","It uses its long, tooth-edged snout to slash through schools of fish and probe the seabed.")
S("shark-dogfish","Spiny dogfish","shark","organisms","shelf","fish","A small, abundant schooling shark with mildly venomous spines, often studied in classrooms.")
S("shark-catshark","Catshark","shark","organisms","deep","inverts","A small bottom shark that lays tough egg cases known as 'mermaid's purses.'")
S("shark-port-jackson","Port Jackson shark","shark","organisms","rocky","crabs","It crushes shellfish with flat back teeth and lays distinctive spiral-shaped egg cases.")
S("shark-zebra","Zebra (leopard) shark","shark","organisms","reef","crabs","Born with stripes that break into spots as it grows, it threads its slender body through reef crevices.")
S("shark-epaulette","Epaulette shark","shark","organisms","reef","inverts","It 'walks' across exposed reef flats on its fins and can survive very low oxygen at low tide.")
S("shark-silky","Silky shark","shark","organisms","open","fish","Smooth-skinned and curious, it is one of the most common open-ocean sharks.")
S("shark-oceanic-whitetip","Oceanic whitetip shark","shark","organisms","open","fishsquid","A bold open-ocean wanderer with rounded, white-tipped fins, once among the most abundant large animals at sea.")

# ============================ RAYS, SKATES & SAWFISH ============================
S("ray-manta","Giant manta ray","ray","organisms","open","plankton","The largest ray, with a wingspan over seven meters, it filters plankton and has the largest brain of any fish.")
S("ray-devil","Devil ray (mobula)","ray","organisms","open","plankton","Smaller cousins of mantas, they sometimes leap and somersault high out of the water in groups.")
S("ray-eagle","Spotted eagle ray","ray","organisms","coast","crabs","Graceful and spotted, it flaps like a bird and uses a duck-like snout to dig clams from the sand.")
S("ray-stingray-southern","Southern stingray","ray","organisms","sand","crabs","It glides over sand and rests buried with only its eyes showing, armed with a venomous tail barb for defense.")
S("ray-bluespotted","Blue-spotted ribbontail ray","ray","organisms","reef","crabs","Vivid blue spots warn of its venomous spines as it forages over coral sand.")
S("ray-electric","Electric ray (torpedo)","ray","organisms","sand","fish","It can deliver a strong electric shock from special organs to stun prey and ward off attackers.")
S("ray-cownose","Cownose ray","ray","organisms","coast","crabs","It travels in large migrating schools and uses its snout to uncover buried shellfish.")
S("ray-sawfish","Sawfish","ray","organisms","mang","fish","Though shaped like a shark, it is a ray; its toothed saw senses and slashes prey, and most species are critically endangered.")
S("ray-guitarfish","Guitarfish","ray","organisms","sand","crabs","A shark-shaped ray that bridges the two groups, cruising sandy shallows for shellfish.")
S("ray-skate","Skate","ray","organisms","shelf","crabs","Unlike most stingrays it has no venomous barb, and it lays eggs in tough cases on the seabed.")
S("ray-manta-reef","Reef manta ray","ray","organisms","reef","plankton","It visits reef 'cleaning stations' where small fish remove parasites, and feeds by funneling plankton with its head fins.")
S("ray-torpedo-marbled","Marbled electric ray","ray","organisms","sand","fish","Camouflaged on the seabed, it ambushes fish and stuns them with an electric jolt.")

# ============================ WHALES (baleen & toothed) ============================
S("mammal-bluewhale","Blue whale","baleen whale (marine mammal)","organisms","open","krill","The largest animal ever to live, it feeds on tiny krill and its low calls are among the loudest made by any animal.")
S("mammal-finwhale","Fin whale","baleen whale (marine mammal)","organisms","open","krill","The second-largest animal, nicknamed the 'greyhound of the sea' for its speed, with oddly asymmetrical jaw coloring.")
S("mammal-humpback","Humpback whale","baleen whale (marine mammal)","organisms","open","krill","Famous for long, complex songs and for blowing nets of bubbles to corral fish before lunging through them.")
S("mammal-graywhale","Gray whale","baleen whale (marine mammal)","organisms","coast","worms","It makes one of the longest mammal migrations and feeds by rolling on its side to suck prey from seafloor mud.")
S("mammal-rightwhale","North Atlantic right whale","baleen whale (marine mammal)","organisms","coast","zoopl","Slow and rich in blubber, it skims clouds of tiny plankton; only a few hundred survive, making it critically endangered.")
S("mammal-bowhead","Bowhead whale","baleen whale (marine mammal)","organisms","polar","zoopl","An Arctic specialist that can break through sea ice and may live over two hundred years.")
S("mammal-minke","Minke whale","baleen whale (marine mammal)","organisms","open","krill","One of the smallest and most common baleen whales, fast and often seen alone.")
S("mammal-seiwhale","Sei whale","baleen whale (marine mammal)","organisms","open","zoopl","One of the fastest whales, it skims through swarms of copepods near the surface.")
S("mammal-spermwhale","Sperm whale","toothed whale (marine mammal)","organisms","deep","squid","It has the largest brain of any animal and dives over a kilometer down to hunt giant squid in the dark.")
S("mammal-pygmysperm","Pygmy sperm whale","toothed whale (marine mammal)","organisms","deep","squid","When startled it releases a cloud of reddish 'ink' to confuse predators as it escapes.")
S("mammal-beaked","Cuvier's beaked whale","toothed whale (marine mammal)","organisms","deep","squid","It holds the record for the deepest and longest dives of any mammal, reaching near three kilometers down.")
S("mammal-narwhal","Narwhal","toothed whale (marine mammal)","organisms","polar","fishsquid","The male's spiraled tusk is actually a giant tooth packed with nerves, earning it the title 'unicorn of the sea.'")
S("mammal-beluga","Beluga whale","toothed whale (marine mammal)","organisms","polar","fish","White and very vocal, it has a flexible neck and a bulging forehead 'melon' it uses to focus sound.")

# ============================ DOLPHINS & PORPOISES ============================
S("mammal-orca","Orca (killer whale)","dolphin (marine mammal)","organisms","global","seals","The largest dolphin and a top ocean predator, it hunts in family pods with distinct cultures and hunting traditions.")
S("mammal-bottlenose","Bottlenose dolphin","dolphin (marine mammal)","organisms","coast","fish","Highly intelligent and social, some use sponges as tools to protect their snouts while foraging.")
S("mammal-common-dolphin","Common dolphin","dolphin (marine mammal)","organisms","open","fish","It travels in fast, leaping 'superpods' that can number in the thousands.")
S("mammal-spinner","Spinner dolphin","dolphin (marine mammal)","organisms","open","fish","Named for leaping and spinning in the air, it rests by day and hunts the twilight zone by night.")
S("mammal-spotted-dolphin","Atlantic spotted dolphin","dolphin (marine mammal)","organisms","coast","fish","Born unspotted, it gains more spots with age until it is heavily speckled.")
S("mammal-risso","Risso's dolphin","dolphin (marine mammal)","organisms","open","squid","Older individuals are crisscrossed with white scars from squid and from social play.")
S("mammal-pilot","Pilot whale","dolphin (marine mammal)","organisms","open","squid","Despite the name it is a large dolphin, living in tight-knit pods that follow elder leaders.")
S("mammal-falsekiller","False killer whale","dolphin (marine mammal)","organisms","open","fishsquid","A large social dolphin known to share food and to interact playfully with other dolphin species.")
S("mammal-harborporpoise","Harbor porpoise","porpoise (marine mammal)","organisms","coast","fish","Small and shy, it must eat almost constantly to fuel its fast metabolism in cool coastal waters.")
S("mammal-dalls","Dall's porpoise","porpoise (marine mammal)","organisms","polar","fish","One of the fastest small cetaceans, it throws up a distinctive 'rooster tail' of spray as it speeds along.")
S("mammal-vaquita","Vaquita","porpoise (marine mammal)","organisms","coast","fish","The world's smallest and most endangered marine mammal, with only a handful left in Mexico's Gulf of California.")
S("mammal-amazon-river","River dolphin","dolphin (marine mammal)","organisms","mang","fish","River dolphins navigate murky water largely by echolocation, and some are tinted pink.")

# ============================ SEALS, SEA LIONS & WALRUS ============================
S("mammal-harborseal","Harbor seal","true seal (marine mammal)","organisms","coast","fish","Its sensitive whiskers can track the invisible wake a fish leaves in the water, even in the dark.")
S("mammal-graysealatl","Gray seal","true seal (marine mammal)","organisms","coast","fish","Recognized by its long, horse-like snout, it hauls out on rocky shores in large breeding colonies.")
S("mammal-elephantseal","Elephant seal","true seal (marine mammal)","organisms","open","squid","The largest seal, the male sports a huge inflatable nose, and it dives deeper and longer than almost any other seal.")
S("mammal-leopardseal","Leopard seal","true seal (marine mammal)","organisms","ice","seals","A powerful Antarctic predator of penguins and other seals, it also filters tiny krill with specialized teeth.")
S("mammal-weddell","Weddell seal","true seal (marine mammal)","organisms","ice","fish","It lives farther south than almost any mammal, gnawing breathing holes in the Antarctic ice.")
S("mammal-crabeater","Crabeater seal","true seal (marine mammal)","organisms","ice","krill","Despite its name it eats krill, sieving them through finely cusped teeth; it may be the most numerous large wild mammal on Earth.")
S("mammal-ross","Ross seal","true seal (marine mammal)","organisms","ice","squid","The smallest and least-seen Antarctic seal, with large eyes and an unusual chirping, siren-like call.")
S("mammal-harp","Harp seal","true seal (marine mammal)","organisms","ice","fish","Its fluffy white pups are born on the sea ice and molt to the harp-marked coat of adults.")
S("mammal-ringed","Ringed seal","true seal (marine mammal)","organisms","ice","fish","The main prey of polar bears, it keeps Arctic breathing holes open all winter using strong claws.")
S("mammal-monkseal","Hawaiian monk seal","true seal (marine mammal)","organisms","tropic","fish","One of the rarest seals, it is a warm-water species found mainly around the Hawaiian Islands.")
S("mammal-bearded","Bearded seal","true seal (marine mammal)","organisms","ice","crabs","Its thick whiskers help it find clams and crabs on the Arctic seabed.")
S("mammal-californiasealion","California sea lion","sea lion (marine mammal)","organisms","coast","fish","Loud and acrobatic, it can rotate its hind flippers to walk on land and is a favorite at marine shows.")
S("mammal-stellersealion","Steller sea lion","sea lion (marine mammal)","organisms","coast","fish","The largest sea lion, the bulls grow huge and defend crowded breeding rookeries.")
S("mammal-fursealnorth","Northern fur seal","fur seal (marine mammal)","organisms","open","fish","Dense fur, not blubber, keeps it warm, and it spends months at sea between breeding seasons.")
S("mammal-walrus","Walrus","walrus (marine mammal)","organisms","ice","crabs","Both sexes bear long tusks used to haul out onto ice and to spar, and it vacuums clams from the seabed with its mouth.")

# ============================ OTHER MARINE MAMMALS ============================
S("mammal-seaotter","Sea otter","sea otter (marine mammal)","organisms","kelp","urchins","Lacking blubber, it relies on the densest fur of any animal and uses rocks as tools to crack open shellfish.")
S("mammal-manatee","Manatee","sirenian (marine mammal)","organisms","mang","plants","A gentle, slow-moving plant-eater of warm shallows, it grazes on seagrass and is sometimes called a 'sea cow.'")
S("mammal-dugong","Dugong","sirenian (marine mammal)","organisms","seagrass","plants","A relative of the manatee with a dolphin-like fluked tail, it grazes seagrass meadows of the Indo-Pacific.")
S("mammal-polarbear","Polar bear","marine mammal (bear)","organisms","ice","seals","Classed as a marine mammal, it hunts seals from the sea ice and can swim for days between ice floes.")

# ============================ SEA TURTLES & MARINE REPTILES ============================
S("reptile-greenturtle","Green sea turtle","sea turtle (reptile)","organisms","seagrass","plants","Unusual among sea turtles, the adult is mostly vegetarian, grazing seagrass and algae; its fat is what gives it a greenish tint.")
S("reptile-loggerhead","Loggerhead turtle","sea turtle (reptile)","organisms","coast","crabs","Its powerful jaws crush hard-shelled prey like crabs and conchs, and it navigates oceans using Earth's magnetic field.")
S("reptile-leatherback","Leatherback turtle","sea turtle (reptile)","organisms","open","jellies","The largest turtle, it has a leathery shell instead of a hard one and feeds almost entirely on jellyfish.")
S("reptile-hawksbill","Hawksbill turtle","sea turtle (reptile)","organisms","reef","sponges","Its narrow beak reaches into reef crevices for sponges, and its beautiful shell has long made it a target of trade.")
S("reptile-oliveridley","Olive ridley turtle","sea turtle (reptile)","organisms","coast","crabs","It is famous for the 'arribada,' when thousands of females come ashore to nest on the same beach at once.")
S("reptile-kempsridley","Kemp's ridley turtle","sea turtle (reptile)","organisms","coast","crabs","The smallest and most endangered sea turtle, it nests mainly on a few beaches in the Gulf of Mexico.")
S("reptile-flatback","Flatback turtle","sea turtle (reptile)","organisms","coast","jellies","Found only around Australia, it has a low, flattened shell and stays close to its home shores.")
S("reptile-seasnake","Sea snake","marine reptile (snake)","organisms","reef","fish","Fully aquatic and highly venomous, it can absorb some oxygen through its skin during long dives.")
S("reptile-seakrait","Sea krait","marine reptile (snake)","organisms","reef","fish","Unlike true sea snakes it returns to land to rest, drink fresh water and lay eggs.")
S("reptile-marineiguana","Marine iguana","marine reptile (lizard)","organisms","rocky","algae","Found only on the Galápagos, it dives to graze underwater algae and sneezes out excess salt.")
S("reptile-saltwatercroc","Saltwater crocodile","marine reptile (crocodile)","organisms","mang","fish","The largest living reptile, it tolerates the sea and can travel long distances between coasts on ocean currents.")

# ============================ SEABIRDS ============================
S("bird-wanderingalbatross","Wandering albatross","seabird","organisms","open","squid","It has the longest wingspan of any bird and can glide thousands of kilometers across the Southern Ocean with barely a wingbeat.")
S("bird-laysanalbatross","Laysan albatross","seabird","organisms","open","squid","It often mates for life and returns to the same nesting island year after year, sometimes for decades.")
S("bird-emperorpenguin","Emperor penguin","seabird (penguin)","organisms","ice","fish","The largest penguin, the male incubates a single egg on his feet through the brutal Antarctic winter.")
S("bird-kingpenguin","King penguin","seabird (penguin)","organisms","polar","fish","It raises its chick over more than a year, and the fluffy brown chicks were once mistaken for a different species.")
S("bird-adeliepenguin","Adélie penguin","seabird (penguin)","organisms","ice","krill","It builds nests of pebbles on the Antarctic coast and porpoises through the water to escape leopard seals.")
S("bird-gentoo","Gentoo penguin","seabird (penguin)","organisms","ice","krill","Recognized by a white head patch, it is the fastest swimming bird, reaching high speeds underwater.")
S("bird-galapagospenguin","Galápagos penguin","seabird (penguin)","organisms","tropic","fish","The only penguin found north of the equator, it relies on cool currents to survive the tropics.")
S("bird-littleblue","Little blue penguin","seabird (penguin)","organisms","coast","fish","The smallest penguin, it comes ashore after dark and nests in burrows along southern coasts.")
S("bird-atlanticpuffin","Atlantic puffin","seabird (auk)","organisms","coast","fish","Its colorful bill can hold many small fish at once, lined up crosswise, as it ferries food to its chick.")
S("bird-commonmurre","Common murre","seabird (auk)","organisms","coast","fish","It nests shoulder to shoulder on bare cliff ledges and 'flies' underwater using its wings to chase fish.")
S("bird-razorbill","Razorbill","seabird (auk)","organisms","coast","fish","A close relative of the extinct great auk, it dives deep on rapid wingbeats to catch fish.")
S("bird-northerngannet","Northern gannet","seabird","organisms","coast","fish","It plunge-dives from high up, hitting the water like an arrow with air sacs cushioning the impact.")
S("bird-bluefoocedbooby","Blue-footed booby","seabird","organisms","coast","fish","The male shows off his bright blue feet in a high-stepping courtship dance; bluer feet signal a healthier bird.")
S("bird-brownpelican","Brown pelican","seabird","organisms","coast","fish","It dives headfirst and scoops fish into the large stretchy pouch under its bill.")
S("bird-frigatebird","Magnificent frigatebird","seabird","organisms","open","fish","The male inflates a huge red throat pouch to attract mates, and it often steals food from other seabirds in midair.")
S("bird-tropicbird","Red-tailed tropicbird","seabird","organisms","open","fishsquid","It ranges far over tropical seas, trailing long tail streamers and plunge-diving for fish and squid.")
S("bird-arctictern","Arctic tern","seabird (tern)","organisms","global","fish","It migrates from the Arctic to the Antarctic and back each year, the longest migration of any animal.")
S("bird-sootytern","Sooty tern","seabird (tern)","organisms","open","fish","It can stay aloft over the ocean for years at a time, snatching prey from the surface without landing.")
S("bird-commontern","Common tern","seabird (tern)","organisms","coast","fish","A graceful diver that hovers then plunges for small fish, nesting in noisy coastal colonies.")
S("bird-herringgull","Herring gull","seabird (gull)","organisms","coast","omni","A clever, adaptable scavenger; chicks peck a red spot on the parent's bill to beg for food.")
S("bird-kittiwake","Black-legged kittiwake","seabird (gull)","organisms","open","fish","Unlike most gulls it spends winters far out at sea and nests on tiny cliff ledges.")
S("bird-cormorant","Cormorant","seabird","organisms","coast","fish","It pursues fish underwater, then must spread its wings to dry because its feathers are not fully waterproof.")
S("bird-shag","European shag","seabird (cormorant)","organisms","rocky","fish","A slender cormorant of rocky coasts, it dives from the surface to chase fish near the seabed.")
S("bird-skua","Great skua","seabird","organisms","open","fish","A piratical seabird that chases others to make them drop their catch, and will defend its nest fiercely.")
S("bird-petrel-storm","Storm petrel","seabird (petrel)","organisms","open","plankton","One of the smallest seabirds, it flutters and 'walks' on the surface to pluck tiny plankton.")
S("bird-shearwater","Shearwater","seabird (petrel)","organisms","open","fish","It shears low over the waves on stiff wings and undertakes vast looping migrations across whole oceans.")
S("bird-fulmar","Northern fulmar","seabird (petrel)","organisms","open","fish","To defend itself it can spit a foul-smelling stomach oil at intruders.")
S("bird-pelagic-auklet","Auklet","seabird (auk)","organisms","coast","plankton","Small and abundant in northern seas, it gathers plankton in huge flocks and nests in rocky crevices.")
S("bird-oystercatcher","Oystercatcher","shorebird (seabird)","organisms","shore","crabs","Its strong chisel-like bill pries open mussels and oysters along the tideline.")

# ============================ CNIDARIANS (jellies, corals, anemones) ============================
S("cnid-moonjelly","Moon jelly","cnidarian (jellyfish)","organisms","coast","plankton","Its four horseshoe-shaped gonads show through a clear bell as it drifts, gently pulsing to stay near the surface.", kind="invert")
S("cnid-lionsmane","Lion's mane jelly","cnidarian (jellyfish)","organisms","polar","plankton","The largest known jellyfish, its mass of fine, stinging tentacles can trail many meters behind the bell.", kind="invert")
S("cnid-boxjelly","Box jellyfish","cnidarian (jellyfish)","organisms","coast","fish","Among the most venomous animals, it has true eyes and swims actively rather than just drifting.", kind="invert")
S("cnid-portuguese","Portuguese man o' war","cnidarian (siphonophore)","organisms","open","fish","Not a single animal but a colony, it sails on a gas-filled float with stinging tentacles hanging below.", kind="invert")
S("cnid-seawasp","Irukandji jellyfish","cnidarian (jellyfish)","organisms","tropic","plankton","Tiny but extremely venomous, this thumbnail-sized box jelly delivers a sting with severe delayed effects.", kind="invert")
S("cnid-cannonball","Cannonball jelly","cnidarian (jellyfish)","organisms","coast","plankton","A firm, round jelly with a mild sting, it is harvested as food in some regions.", kind="invert")
S("cnid-seaanemone","Sea anemone","cnidarian (anemone)","organisms","reef","fish","A flower-like predator anchored to rock, it stuns prey with stinging tentacles and can host clownfish.", kind="invert")
S("cnid-tubeanemone","Tube anemone","cnidarian (anemone)","organisms","sand","plankton","It builds a soft tube in the seabed and withdraws into it in a flash when disturbed.", kind="invert")
S("cnid-staghorn","Staghorn coral","cnidarian (stony coral)","organisms","reef","plankton","A fast-growing, branching reef-builder, it gets much of its food from algae living inside its tissues.", kind="invert")
S("cnid-elkhorn","Elkhorn coral","cnidarian (stony coral)","organisms","reef","plankton","Its broad antler-like branches once dominated Caribbean reefs but are now threatened.", kind="invert")
S("cnid-braincoral","Brain coral","cnidarian (stony coral)","organisms","reef","plankton","Its maze-like grooves give it a brain-like look, and it grows slowly into massive, long-lived boulders.", kind="invert")
S("cnid-firecoral","Fire coral","cnidarian (hydrozoan)","organisms","reef","plankton","Not a true coral but a relative, it delivers a burning sting to careless swimmers.", kind="invert")
S("cnid-softcoral","Soft coral","cnidarian (soft coral)","organisms","reef","plankton","Lacking a hard skeleton, it sways in the current and is stiffened by tiny embedded mineral spikes.", kind="invert")
S("cnid-seafan","Sea fan (gorgonian)","cnidarian (soft coral)","organisms","reef","plankton","It grows as a flat, branching fan oriented across the current to catch drifting plankton.", kind="invert")
S("cnid-seapen","Sea pen","cnidarian (octocoral)","organisms","sand","plankton","Shaped like an old quill pen, this colony anchors in soft sediment and can glow when disturbed.", kind="invert")
S("cnid-blackcoral","Black coral","cnidarian (coral)","organisms","deep","plankton","Slow-growing in deep water, some colonies are among the oldest animals on Earth, living thousands of years.", kind="invert")
S("cnid-hydroid","Hydroid","cnidarian (hydrozoan)","organisms","rocky","plankton","Feathery colonies of tiny polyps coat rocks and seaweed, catching plankton with stinging cells.", kind="invert")
S("cnid-bluebottle-bythewind","By-the-wind sailor","cnidarian (hydrozoan)","organisms","open","plankton","A small floating colony with a stiff sail that catches the wind, often washing ashore in great numbers.", kind="invert")
S("cnid-combjelly","Comb jelly (ctenophore)","comb jelly","organisms","open","plankton","It swims with shimmering rows of beating combs and catches prey with sticky cells rather than stings.", kind="invert")

# ============================ CEPHALOPODS ============================
S("ceph-giantpacific","Giant Pacific octopus","mollusc (cephalopod)","organisms","rocky","crabs","The largest octopus, it is a clever escape artist that can squeeze its boneless body through any gap bigger than its beak.", kind="invert")
S("ceph-common","Common octopus","mollusc (cephalopod)","organisms","reef","crabs","A problem-solver that opens jars and uses shells as shelter, it can change color and texture in an instant.", kind="invert")
S("ceph-bluering","Blue-ringed octopus","mollusc (cephalopod)","organisms","reef","crabs","Tiny but deadly, it flashes electric-blue rings as a warning and carries a powerful paralytic toxin.", kind="invert")
S("ceph-mimic","Mimic octopus","mollusc (cephalopod)","organisms","sand","crabs","It can impersonate other animals, such as a flatfish, lionfish or sea snake, by reshaping its body and posture.", kind="invert")
S("ceph-dumbo","Dumbo octopus","mollusc (cephalopod)","organisms","deep","inverts","Named for ear-like fins, it is among the deepest-living octopuses, flapping gently above the abyssal floor.", kind="invert")
S("ceph-coconut","Coconut octopus","mollusc (cephalopod)","organisms","sand","crabs","It carries coconut or clam shells to assemble into portable armor, a rare example of tool use in an invertebrate.", kind="invert")
S("ceph-giantsquid","Giant squid","mollusc (cephalopod)","organisms","deep","fish","One of the largest invertebrates, with eyes the size of dinner plates, it was first filmed alive only recently.", kind="invert")
S("ceph-colossal","Colossal squid","mollusc (cephalopod)","organisms","deep","fish","The heaviest invertebrate, it has swiveling hooks on its arms and the largest eyes of any known animal.", kind="invert")
S("ceph-humboldt","Humboldt squid","mollusc (cephalopod)","organisms","deep","fish","A large, aggressive hunter that gathers in huge shoals and flashes red and white, earning the nickname 'red devil.'", kind="invert")
S("ceph-vampire","Vampire squid","mollusc (cephalopod)","organisms","deep","detritus","Neither squid nor octopus, this deep-sea relict eats sinking 'marine snow' and can turn itself inside out to hide.", kind="invert")
S("ceph-bobtail","Bobtail squid","mollusc (cephalopod)","organisms","sand","inverts","It hides its silhouette using glowing bacteria housed in a special light organ, matching the moonlight above.", kind="invert")
S("ceph-reefsquid","Caribbean reef squid","mollusc (cephalopod)","organisms","reef","fish","It communicates with rippling color patterns and can even send different signals from each side of its body.", kind="invert")
S("ceph-cuttlefish","Cuttlefish","mollusc (cephalopod)","organisms","reef","crabs","A camouflage champion, it controls its skin with split-second precision and floats using a porous internal 'cuttlebone.'", kind="invert")
S("ceph-flamboyant","Flamboyant cuttlefish","mollusc (cephalopod)","organisms","sand","crabs","Small and toxic, it pulses with vivid colors and 'walks' along the seabed on arm-like flaps.", kind="invert")
S("ceph-nautilus","Chambered nautilus","mollusc (cephalopod)","organisms","deep","detritus","A 'living fossil' with a coiled, gas-filled shell, it adjusts its buoyancy by emptying and filling the chambers.", kind="invert")
S("ceph-paper-nautilus","Argonaut (paper nautilus)","mollusc (cephalopod)","organisms","open","jellies","The female secretes a delicate, papery shell that she uses as an egg case and a buoyancy aid.", kind="invert")

# ============================ GASTROPODS & SEA SLUGS ============================
S("gast-conch","Queen conch","mollusc (gastropod)","organisms","seagrass","algae","It grazes algae in seagrass beds and grows a large pink-lipped shell; it moves in odd hops using a claw-like foot.", kind="invert")
S("gast-coneshell","Cone snail","mollusc (gastropod)","organisms","reef","fish","It harpoons prey with a venom-loaded tooth; some species' venom is potent enough to harm humans, but is also studied for medicines.", kind="invert")
S("gast-cowrie","Cowrie","mollusc (gastropod)","organisms","reef","algae","Its glossy shell stays polished because the snail's soft mantle folds up over it; cowries were once used as money.", kind="invert")
S("gast-abalone","Abalone","mollusc (gastropod)","organisms","kelp","algae","It clamps to rock with a strong foot and lines its ear-shaped shell with shimmering mother-of-pearl.", kind="invert")
S("gast-limpet","Limpet","mollusc (gastropod)","organisms","rocky","algae","It grips rock so tightly that waves cannot dislodge it, and returns to the exact same 'home scar' after grazing.", kind="invert")
S("gast-periwinkle","Periwinkle","mollusc (gastropod)","organisms","rocky","algae","A hardy shoreline snail, it seals itself inside its shell to survive being exposed at low tide.", kind="invert")
S("gast-whelk","Whelk","mollusc (gastropod)","organisms","sand","crabs","A predatory sea snail, it drills or pries open clams and other shellfish to feed.", kind="invert")
S("gast-murex","Murex","mollusc (gastropod)","organisms","rocky","crabs","Spiny and predatory, ancient peoples extracted a precious purple dye from murex snails.", kind="invert")
S("gast-tritontrumpet","Triton's trumpet","mollusc (gastropod)","organisms","reef","urchins","One of the few predators of the destructive crown-of-thorns starfish, it grows a large trumpet-shaped shell.", kind="invert")
S("gast-nudibranch","Nudibranch (sea slug)","mollusc (sea slug)","organisms","reef","inverts","A shell-less, often dazzlingly colorful slug, some steal stinging cells from their prey to reuse in their own defense.", kind="invert")
S("gast-spanishdancer","Spanish dancer","mollusc (sea slug)","organisms","reef","sponges","A large red sea slug that 'dances' by flexing its frilly body to swim through the water.", kind="invert")
S("gast-seahare","Sea hare","mollusc (sea slug)","organisms","seagrass","algae","When threatened it releases a cloud of purple ink, and it grazes seaweed with ear-like flaps on its head.", kind="invert")
S("gast-seabutterfly","Sea butterfly (pteropod)","mollusc (sea slug)","organisms","open","plankton","A tiny swimming snail that 'flies' through the water on wing-like flaps; its thin shell is vulnerable to ocean acidification.", kind="invert")
S("gast-blueglaucus","Blue dragon (glaucus)","mollusc (sea slug)","organisms","open","jellies","It floats upside down at the surface eating venomous siphonophores, then stores their stings for its own defense.", kind="invert")
S("gast-seaslug-lettuce","Lettuce sea slug","mollusc (sea slug)","organisms","reef","photosyn","It keeps working chloroplasts from the algae it eats, letting it make some of its own food from sunlight.", kind="invert")

# ============================ BIVALVES & CHITONS ============================
S("biv-giantclam","Giant clam","mollusc (bivalve)","organisms","reef","photosyn","The largest clam, it grows algae in its colorful mantle and gets much of its food from their photosynthesis.", kind="invert")
S("biv-scallop","Scallop","mollusc (bivalve)","organisms","sand","filter","It can swim in bursts by clapping its shells, and rows of tiny blue eyes line the edge of its mantle.", kind="invert")
S("biv-oyster","Oyster","mollusc (bivalve)","organisms","coast","filter","It filters and cleans large volumes of water, builds reefs that shelter other life, and can produce pearls.", kind="invert")
S("biv-mussel","Blue mussel","mollusc (bivalve)","organisms","rocky","filter","It anchors to rock with tough threads it spins, and clusters in dense beds between the tides.", kind="invert")
S("biv-cockle","Cockle","mollusc (bivalve)","organisms","sand","filter","A ribbed, heart-shaped clam, it burrows shallowly and can hop using a strong muscular foot.", kind="invert")
S("biv-razor","Razor clam","mollusc (bivalve)","organisms","sand","filter","Long and narrow, it is a champion burrower, vanishing into wet sand in seconds.", kind="invert")
S("biv-shipworm","Shipworm","mollusc (bivalve)","organisms","coast","detritus","Not a worm but a clam, it bores into wood and digests it with the help of symbiotic bacteria.", kind="invert")
S("biv-pen-shell","Pen shell","mollusc (bivalve)","organisms","seagrass","filter","A large, fan-shaped clam that stands upright anchored in seagrass beds by fine golden threads.", kind="invert")
S("biv-quahog","Ocean quahog","mollusc (bivalve)","organisms","sand","filter","This slow-growing clam is among the longest-lived animals; one was found to be about five centuries old.", kind="invert")
S("biv-angelwing","Angel wing clam","mollusc (bivalve)","organisms","mang","filter","Its fragile white shell, ribbed like a wing, hides a clam that burrows deep into soft mud.", kind="invert")
S("moll-chiton","Chiton","mollusc (chiton)","organisms","rocky","algae","Its shell is made of eight overlapping plates, letting it curl up and grip uneven rock as it grazes algae.", kind="invert")

# ============================ CRUSTACEANS ============================
S("crus-hermitcrab","Hermit crab","crustacean","organisms","rocky","detritus","With a soft, vulnerable abdomen, it lives inside an empty snail shell and trades up to bigger shells as it grows.", kind="invert")
S("crus-fiddlercrab","Fiddler crab","crustacean","organisms","mang","detritus","The male waves one greatly enlarged claw to attract mates and warn off rivals on the mudflats.", kind="invert")
S("crus-ghostcrab","Ghost crab","crustacean","organisms","shore","omni","Pale and fast, it digs burrows on sandy beaches and is most active at night.", kind="invert")
S("crus-bluecrab","Blue crab","crustacean","organisms","mang","omni","A prized seafood species, it swims using paddle-shaped back legs and is a fierce scavenger and predator.", kind="invert")
S("crus-dungeness","Dungeness crab","crustacean","organisms","shelf","crabs","A large, sweet-meated crab of the Pacific coast supporting an important fishery.", kind="invert")
S("crus-kingcrab","King crab","crustacean","organisms","polar","detritus","A huge, long-legged crab of cold deep waters, it is among the most valuable seafood catches.", kind="invert")
S("crus-snowcrab","Snow crab","crustacean","organisms","polar","detritus","A cold-water crab with long spindly legs, harvested across the northern seas.", kind="invert")
S("crus-spidercrab","Japanese spider crab","crustacean","organisms","deep","detritus","It has the largest leg span of any arthropod, stretching several meters from claw to claw.", kind="invert")
S("crus-coconutcrab","Coconut crab","crustacean (land)","organisms","shore","omni","The largest land arthropod, this giant hermit-crab relative can climb trees and crack open coconuts.", kind="invert")
S("crus-porcelaincrab","Porcelain crab","crustacean","organisms","reef","plankton","It sweeps plankton from the water with feathery mouthparts and sheds a leg easily to escape danger.", kind="invert")
S("crus-decoratorcrab","Decorator crab","crustacean","organisms","reef","detritus","It camouflages by attaching bits of sponge, algae and anemones to hooks on its shell.", kind="invert")
S("crus-spinylobster","Spiny lobster","crustacean","organisms","reef","inverts","Lacking big claws, it relies on spiny armor and migrates in long single-file lines across the seabed.", kind="invert")
S("crus-americanlobster","American lobster","crustacean","organisms","rocky","inverts","It wields one heavy crusher claw and one sharp cutter claw, and can live for many decades.", kind="invert")
S("crus-slipperlobster","Slipper lobster","crustacean","organisms","reef","inverts","Flat and shovel-nosed, it lacks long antennae and shelters in reef crevices by day.", kind="invert")
S("crus-mantisshrimp","Mantis shrimp","crustacean","organisms","reef","crabs","It strikes with club-like limbs so fast they boil the water, and it has some of the most complex eyes known.", kind="invert")
S("crus-pistolshrimp","Pistol shrimp","crustacean","organisms","reef","inverts","It snaps a specialized claw to create a shockwave loud enough to stun prey.", kind="invert")
S("crus-cleanershrimp","Cleaner shrimp","crustacean","organisms","reef","parasites","It sets up a cleaning station, picking parasites from fish that hold still and even open their mouths for it.", kind="invert")
S("crus-krill","Antarctic krill","crustacean (krill)","organisms","polar","plankton","Tiny but astronomically abundant, swarms of krill feed whales, seals and penguins and form a pillar of the Antarctic food web.", kind="invert")
S("crus-copepod","Copepod","crustacean (plankton)","organisms","open","plankton","Among the most numerous animals on Earth, these tiny drifters are a key link between phytoplankton and larger animals.", kind="invert")
S("crus-amphipod","Amphipod","crustacean","organisms","deep","detritus","These shrimp-like scavengers swarm whale falls and even thrive in the deepest ocean trenches.", kind="invert")
S("crus-isopod-giant","Giant isopod","crustacean","organisms","deep","detritus","A deep-sea relative of the pillbug, it can grow surprisingly large and survive long stretches between meals.", kind="invert")
S("crus-barnacle","Barnacle","crustacean","organisms","rocky","filter","Cemented head-down to rock, it kicks feathery legs out of its shell to comb plankton from the water.", kind="invert")
S("crus-goosebarnacle","Goose barnacle","crustacean","organisms","open","filter","It attaches by a flexible stalk to floating debris and was once believed to hatch into geese.", kind="invert")
S("crus-horseshoecrab","Horseshoe crab","chelicerate (not a true crab)","organisms","coast","worms","A 'living fossil' more closely related to spiders than crabs, its blue, copper-based blood is used to test medicines for safety.", kind="invert")
S("crus-sandhopper","Sand hopper","crustacean","organisms","shore","detritus","It burrows in damp beach sand by day and emerges at night to feed on washed-up seaweed.", kind="invert")

# ============================ ECHINODERMS ============================
S("echi-seastar","Sea star (starfish)","echinoderm","organisms","rocky","crabs","It can push its stomach out through its mouth to digest prey, and can regrow a lost arm.", kind="invert")
S("echi-crownofthorns","Crown-of-thorns starfish","echinoderm","organisms","reef","coral","A spiny coral-eater, its population outbreaks can strip large areas of reef.", kind="invert")
S("echi-sunflowerstar","Sunflower star","echinoderm","organisms","kelp","urchins","One of the largest and fastest sea stars, with up to two dozen arms; its decline has let urchins overgraze kelp.", kind="invert")
S("echi-brittlestar","Brittle star","echinoderm","organisms","reef","detritus","It scuttles surprisingly fast on slender, flexible arms and readily drops an arm to escape predators.", kind="invert")
S("echi-basketstar","Basket star","echinoderm","organisms","deep","plankton","At night it unfurls finely branching arms into a living net to trap drifting plankton.", kind="invert")
S("echi-seaurchin","Sea urchin","echinoderm","organisms","rocky","algae","A spiny grazer, it scrapes algae with a five-toothed mouth structure known as 'Aristotle's lantern.'", kind="invert")
S("echi-pencilurchin","Slate pencil urchin","echinoderm","organisms","reef","algae","Thick, blunt spines like colored pencils protect it and help wedge it into reef crevices.", kind="invert")
S("echi-sanddollar","Sand dollar","echinoderm","organisms","sand","detritus","A flattened urchin relative, it burrows just under the sand and is covered in tiny moving spines in life.", kind="invert")
S("echi-seacucumber","Sea cucumber","echinoderm","organisms","sand","detritus","It recycles seafloor sediment as it feeds, and some species eject sticky threads or their own organs to deter predators.", kind="invert")
S("echi-featherstar","Feather star (crinoid)","echinoderm","organisms","reef","plankton","An ancient echinoderm, it perches with feathery arms spread to catch plankton and can even swim by waving them.", kind="invert")
S("echi-seapig","Sea pig","echinoderm","organisms","deep","detritus","A plump, pinkish sea cucumber that walks on tube-feet across the abyssal plain, hoovering up nutritious mud.", kind="invert")
S("echi-seaapple","Sea apple","echinoderm","organisms","reef","plankton","A colorful sea cucumber that fans out branching tentacles to filter plankton from the current.", kind="invert")

# ============================ WORMS & OTHER SOFT INVERTEBRATES ============================
S("worm-bristle","Bristle worm","marine worm (polychaete)","organisms","reef","detritus","Each body segment bears bundles of bristles; some, called fireworms, carry irritating spines for defense.", kind="invert")
S("worm-christmastree","Christmas tree worm","marine worm (polychaete)","organisms","reef","filter","It anchors in coral and fans out two colorful spiral crowns to filter food, snapping them in instantly if disturbed.", kind="invert")
S("worm-featherduster","Feather duster worm","marine worm (polychaete)","organisms","sand","filter","From a leathery tube it unfurls a feathery crown to strain plankton, withdrawing in a flash when threatened.", kind="invert")
S("worm-tubeworm-vent","Giant tube worm","marine worm (vent)","organisms","vent","chemo","Living at hydrothermal vents, it has no mouth or gut and is fed entirely by symbiotic bacteria inside its body.", kind="invert")
S("worm-osedax","Bone-eating worm (Osedax)","marine worm","organisms","deep","chemo","These 'zombie worms' bore into the bones of whale falls, mining the fats inside with the help of bacteria.", kind="invert")
S("worm-flatworm","Marine flatworm","marine worm (flatworm)","organisms","reef","inverts","Paper-thin and often vividly colored, it glides by rippling its edges and some mimic toxic sea slugs.", kind="invert")
S("worm-ribbonworm","Ribbon worm (nemertean)","marine worm","organisms","sand","inverts","It can stretch many times its resting length and shoots out a sticky or venomous proboscis to capture prey.", kind="invert")
S("worm-arrowworm","Arrow worm","marine worm (chaetognath)","organisms","open","plankton","A transparent planktonic hunter, it seizes tiny prey with grasping spines around its mouth.", kind="invert")
S("worm-peanutworm","Peanut worm (sipunculan)","marine worm","organisms","sand","detritus","It can pull its front end inside its body, taking on a peanut-like shape when contracted.", kind="invert")
S("worm-innkeeper","Innkeeper worm (echiuran)","marine worm","organisms","sand","filter","It pumps water through a U-shaped burrow using a mucus net, and other animals lodge in the burrow as 'guests.'", kind="invert")
S("worm-palolo","Palolo worm","marine worm (polychaete)","organisms","reef","detritus","On certain moonlit nights its tail segments swarm to the surface in a mass spawning so predictable people harvest them.", kind="invert")

# ============================ SPONGES & TUNICATES ============================
S("spng-barrelsponge","Giant barrel sponge","sponge","organisms","reef","filter","Big enough to sit inside, this slow-growing sponge filters huge volumes of water and can live for centuries.", kind="invert")
S("spng-glasssponge","Glass sponge","sponge","organisms","deep","filter","Its skeleton is built of delicate silica glass, and deep-water 'gardens' of them can form on the seafloor.", kind="invert")
S("spng-venusflower","Venus' flower basket","sponge","organisms","deep","filter","A lattice of glassy fibers, it often shelters a pair of shrimp that live their whole lives sealed inside.", kind="invert")
S("spng-encrusting","Encrusting sponge","sponge","organisms","reef","filter","It spreads as a colorful crust over rocks and reefs, drawing water in through countless tiny pores.", kind="invert")
S("tuni-seasquirt","Sea squirt","tunicate","organisms","rocky","filter","A sac-like filter feeder, it squirts water when poked; though it looks like a blob, it is a close relative of vertebrates.", kind="invert")
S("tuni-salp","Salp","tunicate (salp)","organisms","open","filter","A barrel-shaped drifter that pumps water through its body to feed and can rapidly form long chains.", kind="invert")
S("tuni-pyrosome","Pyrosome","tunicate (colony)","organisms","open","filter","A tube-shaped colony of thousands of tiny animals, it drifts as one and glows with brilliant bioluminescence.", kind="invert")
S("tuni-lightbulb","Light bulb tunicate","tunicate","organisms","reef","filter","Named for its glassy, bulb-like bodies, it grows in clusters that filter plankton from the water.", kind="invert")

# ============================ PLANKTON & MICROBES ============================
S("plank-diatom","Diatom","phytoplankton (diatom)","organisms","open","photosyn","Encased in an ornate, two-part shell of glassy silica, diatoms drift in sunlit water and produce a large share of Earth's oxygen.", kind="ecology")
S("plank-dinoflagellate","Dinoflagellate","phytoplankton (dinoflagellate)","organisms","open","photosyn","These spinning, two-tailed cells include species that cause harmful 'red tides' and others that light the waves with bioluminescence.", kind="ecology")
S("plank-coccolithophore","Coccolithophore","phytoplankton","organisms","open","photosyn","It armors itself in tiny chalk plates, and its blooms can turn whole seas milky and be seen from space.", kind="ecology")
S("plank-cyanobacteria","Prochlorococcus","cyanobacteria (microbe)","organisms","open","photosyn","Possibly the most abundant photosynthetic organism on Earth, this microscopic cell helps generate much of the oxygen we breathe.", kind="ecology")
S("plank-foram","Foraminifera","plankton (protist)","organisms","open","plankton","It builds a chalky shell, and countless fallen foram shells form thick seafloor ooze that hardens into chalk and limestone.", kind="ecology")
S("plank-radiolaria","Radiolaria","plankton (protist)","organisms","open","plankton","These drifters spin intricate, glassy mineral skeletons of astonishing geometric beauty.", kind="ecology")
S("plank-noctiluca","Sea sparkle (Noctiluca)","plankton (dinoflagellate)","organisms","coast","plankton","When disturbed at night it flashes blue, making breaking waves and boat wakes glow with bioluminescence.", kind="ecology")
S("plank-trichodesmium","Trichodesmium","cyanobacteria (microbe)","organisms","open","photosyn","It forms rusty surface slicks sometimes called 'sea sawdust' and pulls nitrogen from the air to fertilize the sea.", kind="ecology")
S("microbe-virus","Marine virus","marine microbe (virus)","organisms","open","","The most numerous biological particles in the sea, marine viruses help recycle nutrients by bursting the microbes they infect.", kind="ecology")
S("microbe-archaea","Marine archaea","marine microbe (archaea)","organisms","vent","chemo","These ancient single-celled microbes thrive in extreme places like hot vents, often living on chemical energy.", kind="ecology")
S("microbe-bacterioplankton","Bacterioplankton","marine microbe (bacteria)","organisms","open","detritus","Invisible but vital, ocean bacteria break down dead matter and recycle nutrients that fuel the entire food web.", kind="ecology")
S("plank-larva","Planktonic larva","plankton (animal larva)","organisms","open","plankton","Many crabs, fish and sea stars begin life as tiny drifting larvae that look nothing like their parents and ride currents to new homes.", kind="ecology")

# ============================ ALGAE, SEAGRASSES & MANGROVES ============================
S("algae-giantkelp","Giant kelp","brown alga (kelp)","organisms","kelp","photosyn","Among the fastest-growing organisms, it floats on gas-filled bladders to build towering underwater forests.", kind="ecology")
S("algae-bullkelp","Bull kelp","brown alga (kelp)","organisms","kelp","photosyn","A single round float buoys its long whip-like stalk, and it grows an entire forest in just one season.", kind="ecology")
S("algae-sargassum","Sargassum","brown alga (sargassum)","organisms","open","photosyn","It floats in vast drifting mats, and the Sargasso Sea it forms shelters baby turtles, crabs and fish far from land.", kind="ecology")
S("algae-sealettuce","Sea lettuce (Ulva)","green alga","organisms","rocky","photosyn","Thin, translucent green sheets cling to tidal rocks and thrive where nutrients are plentiful.", kind="ecology")
S("algae-coralline","Coralline algae","red alga (calcified)","organisms","reef","photosyn","It lays down hard limestone, helping cement reefs together and signaling to coral larvae where to settle.", kind="ecology")
S("algae-nori","Nori (Porphyra)","red alga","organisms","rocky","photosyn","This thin red seaweed is dried into the dark sheets used to wrap sushi.", kind="ecology")
S("algae-kombu","Kombu","brown alga (kelp)","organisms","coast","photosyn","A thick, edible kelp, it is simmered to make dashi, the savory, umami-rich broth at the heart of Japanese cooking.", kind="ecology")
S("algae-caulerpa","Caulerpa","green alga","organisms","sand","photosyn","Remarkably, a sprawling Caulerpa is essentially one giant cell, and some strains have become aggressive invaders.", kind="ecology")
S("algae-halimeda","Halimeda","green alga (calcified)","organisms","reef","photosyn","Its chalky, segmented joints crumble after death into vast amounts of fine white reef sand.", kind="ecology")
S("algae-irishmoss","Irish moss (Chondrus)","red alga","organisms","rocky","photosyn","A cold-water seaweed, it yields carrageenan, a thickener used in many foods.", kind="ecology")
S("plant-eelgrass","Eelgrass","seagrass (flowering plant)","organisms","seagrass","photosyn","A true flowering plant rather than an alga, it forms meadows that nurse young fish and lock away 'blue carbon.'", kind="ecology")
S("plant-turtlegrass","Turtle grass","seagrass (flowering plant)","organisms","seagrass","photosyn","Its broad blades feed sea turtles and manatees and stabilize the seabed across the Caribbean.", kind="ecology")
S("plant-posidonia","Neptune grass (Posidonia)","seagrass (flowering plant)","organisms","seagrass","photosyn","Some Mediterranean meadows are single clones thousands of years old, among the oldest living things on Earth.", kind="ecology")
S("plant-manateegrass","Manatee grass","seagrass (flowering plant)","organisms","seagrass","photosyn","Named for its grazers, it has rounded, cylindrical blades unlike most flat-bladed seagrasses.", kind="ecology")
S("plant-redmangrove","Red mangrove","mangrove tree","organisms","mang","photosyn","Its arching stilt roots trap sediment, buffer storms and create sheltered nurseries for countless young fish.", kind="ecology")
S("plant-blackmangrove","Black mangrove","mangrove tree","organisms","mang","photosyn","It sends up pencil-like roots from the mud to breathe and sheds excess salt through its leaves.", kind="ecology")
S("plant-cordgrass","Saltmarsh cordgrass","salt-marsh grass","organisms","shore","photosyn","It engineers entire salt marshes, trapping mud and feeding rich estuarine food webs.", kind="ecology")

# ============================ MORE FISHES (reef, coastal & temperate) ============================
S("fish-hogfish","Hogfish","wrasse","organisms","reef","crabs","It roots in sand with a pig-like snout for shellfish, and every hogfish starts life female before some become male.")
S("fish-napoleonwrasse","Humphead (Napoleon) wrasse","wrasse","organisms","reef","inverts","A giant, long-lived reef fish with a bulbous forehead, it is one of the few predators of the coral-eating crown-of-thorns starfish.")
S("fish-dottyback","Dottyback","dottyback","organisms","reef","inverts","Small and pugnacious, some can shift color to blend in with other fish and sneak up on prey.")
S("fish-jawfish","Jawfish","jawfish","organisms","sand","plankton","It digs a pebble-lined burrow and the male broods the eggs in his mouth until they hatch.")
S("fish-firefish","Firefish (dartfish)","dartfish","organisms","reef","plankton","It hovers above its burrow snatching plankton and darts back inside at the first sign of danger.")
S("fish-tilefish","Tilefish","tilefish","organisms","sand","crabs","It excavates burrows and mounds in the seafloor, creating shelter used by many other animals.")
S("fish-wolffish","Atlantic wolffish","wolffish","organisms","rocky","urchins","Strong jaws and crushing teeth let it eat urchins and crabs, and it makes a natural antifreeze to survive frigid water.")
S("fish-lumpsucker","Lumpsucker","lumpsucker","organisms","rocky","plankton","A rounded, bumpy fish, it clings to rocks with a suction disc formed from modified fins.")
S("fish-sculpin","Sculpin","sculpin","organisms","rocky","inverts","A big-headed, well-camouflaged bottom fish that ambushes small prey among rocks and tide pools.")
S("fish-rockfish","Rockfish","rockfish","organisms","rocky","fish","Some rockfish live over a century, and many carry venomous spines for defense.")
S("fish-greenling","Greenling","greenling","organisms","kelp","inverts","A patterned fish of kelp and rocky reefs, the male guards the eggs until they hatch.")
S("fish-cod","Atlantic cod","cod","organisms","shelf","fish","Once supporting some of history's greatest fisheries, it has a chin barbel for sensing food on the bottom.")
S("fish-haddock","Haddock","cod relative","organisms","shelf","inverts","A bottom-feeding relative of cod, marked by a dark 'thumbprint' spot on each side.")
S("fish-pollock","Pollock","cod relative","organisms","shelf","fish","A fast-schooling cod relative, it is one of the most heavily fished species in the world.")
S("fish-hake","Hake","cod relative","organisms","shelf","fish","A slender, deep-water cod relative that rises at night to hunt smaller fish.")
S("fish-surfperch","Surfperch","surfperch","organisms","coast","inverts","Unusual among bony fish, it gives birth to live, fully formed young in the surf zone.")
S("fish-blackdrum","Black drum","drum","organisms","coast","crabs","It produces deep drumming sounds with its swim bladder and crushes shellfish with strong throat teeth.")
S("fish-croaker","Croaker","drum","organisms","sand","inverts","Named for the croaking noises it makes, it forages over soft bottoms for small invertebrates.")
S("fish-reddrum","Red drum","drum","organisms","coast","crabs","A spot near its tail may trick predators into striking the wrong end as it feeds in the shallows.")
S("fish-sheepshead","Sheepshead","porgy relative","organisms","coast","crabs","Its broad, human-like teeth crunch through barnacles, crabs and oysters around pilings and rocks.")
S("fish-porgy","Porgy","porgy","organisms","coast","inverts","A deep-bodied coastal fish with strong teeth for crushing small shelled prey.")
S("fish-trumpetfish","Trumpetfish","trumpetfish","organisms","reef","fish","It hovers head-down among soft corals and even shadows larger fish to sneak up on prey, then sucks it in.")
S("fish-cornetfish","Cornetfish","cornetfish","organisms","reef","fish","Extremely long and thin with a whip-like tail filament, it stalks small fish over reefs and seagrass.")
S("fish-pineconefish","Pineconefish","pineconefish","organisms","reef","plankton","Armored in plate-like scales, it carries light organs that glow thanks to symbiotic bacteria.")
S("fish-grunion","Grunion","silverside","organisms","coast","plankton","It rides waves onto the beach to spawn in the wet sand on certain moonlit high tides.")
S("fish-sandlance","Sand lance","sand lance","organisms","sand","plankton","It dives into loose sand to hide and is a crucial forage fish for seabirds, whales and larger fish.")
S("fish-icefish","Antarctic icefish","icefish","organisms","polar","krill","It survives sub-zero seas with antifreeze proteins, and remarkably its blood carries no red cells at all.")
S("fish-silverside","Silverside","silverside","organisms","coast","plankton","Small and shiny, it schools near the surface in shallows and is important food for larger predators.")

# ============================ MORE SHARKS & RAYS ============================
S("shark-bonnethead","Bonnethead shark","shark","organisms","coast","crabs","A small, shovel-headed hammerhead, it is the only shark known to deliberately eat and digest seagrass.")
S("shark-salmon","Salmon shark","shark","organisms","polar","fish","A warm-bodied, fast Pacific relative of the great white, it thrives in cold northern waters.")
S("shark-porbeagle","Porbeagle","shark","organisms","open","fish","Stocky and warm-bodied, it is a strong swimmer of cool seas and a close cousin of the mako.")
S("shark-sixgill","Bluntnose sixgill shark","shark","organisms","deep","fishsquid","A large, primitive deep-sea shark with six gill slits instead of the usual five, it rises toward the surface at night.")
S("shark-sevengill","Broadnose sevengill shark","shark","organisms","coast","fish","One of the few sharks with seven gill slits, it hunts cooperatively in kelp beds and bays.")
S("shark-swell","Swell shark","shark","organisms","reef","inverts","When threatened it gulps water to swell up and wedge itself into a crevice so predators cannot remove it.")
S("shark-horn","Horn shark","shark","organisms","rocky","crabs","Small and slow, it crushes hard-shelled prey with flat back teeth and lays spiral-shaped egg cases.")
S("shark-bamboo","Bamboo shark","carpet shark","organisms","reef","inverts","A small, slender bottom shark that can survive low oxygen at low tide and lays tough egg cases.")
S("shark-leopard-pacific","Leopard shark","shark","organisms","coast","crabs","Boldly saddled and spotted, it gathers in large groups over sandy flats and reefs of the Pacific coast.")
S("shark-smoothhound","Smooth-hound","shark","organisms","coast","crabs","A small, harmless coastal shark with flat teeth for grinding up crabs and shellfish.")
S("ray-batray","Bat ray","ray","organisms","bay","crabs","It flaps along the bottom of bays and uncovers buried clams by fanning away sand with its wings.")
S("ray-pelagic-stingray","Pelagic stingray","ray","organisms","open","squid","Unlike most stingrays, it lives out in the open ocean rather than resting on the seabed.")

# ============================ MORE INVERTEBRATES (reaches 444 generated) ============================
S("crus-stonecrab","Stone crab","crustacean","organisms","rocky","inverts","Fishers harvest just one of its claws and return it alive, since the crab can regrow the missing claw.", kind="invert")
S("crus-mudcrab","Mangrove mud crab","crustacean","organisms","mang","omni","A large, powerful crab of mangrove mud, prized as seafood and armed with heavy crushing claws.", kind="invert")
S("crus-arrowcrab","Arrow crab","crustacean","organisms","reef","inverts","With a pointed head and impossibly long, spindly legs, it looks like a daddy longlegs of the reef.", kind="invert")
S("crus-sallylightfoot","Sally Lightfoot crab","crustacean","organisms","shore","omni","Brightly colored and lightning-fast, it skitters across wave-splashed tropical rocks almost too quick to catch.", kind="invert")
S("crus-peacrab","Pea crab","crustacean","organisms","coast","detritus","Tiny and soft, it lives sheltered inside the shells of oysters and mussels, sharing its host's filtered food.", kind="invert")
S("crus-boxercrab","Boxer (pom-pom) crab","crustacean","organisms","reef","detritus","It carries a small stinging anemone in each claw, waving them like pom-poms to fend off predators.", kind="invert")
S("crus-kelpcrab","Kelp crab","crustacean","organisms","kelp","algae","It clambers through kelp fronds grazing on algae and can deliver a sharp pinch in defense.", kind="invert")
S("crus-boxcrab","Box (shame-faced) crab","crustacean","organisms","sand","crabs","It folds its broad claws over its face like a mask and burrows into sand to hide.", kind="invert")
S("crus-harlequinshrimp","Harlequin shrimp","crustacean","organisms","reef","inverts","Strikingly patterned, pairs hunt sea stars together, flipping them over to feed slowly on the living animal.", kind="invert")
S("crus-bandedcoralshrimp","Banded coral shrimp","crustacean","organisms","reef","parasites","With long white antennae, it runs a cleaning station, picking parasites from fish that come to be groomed.", kind="invert")
S("crus-peppermintshrimp","Peppermint shrimp","crustacean","organisms","reef","inverts","Red-striped and helpful in aquariums, it eats nuisance anemones and cleans up scraps.", kind="invert")
S("crus-ghostshrimp","Ghost shrimp","crustacean","organisms","sand","detritus","A pale burrowing shrimp, it digs deep tunnel networks that stir and aerate the seabed.", kind="invert")
S("crus-anemoneshrimp","Anemone shrimp","crustacean","organisms","reef","parasites","Immune to the stings, it lives among anemone tentacles and cleans visiting fish.", kind="invert")
S("crus-emperorshrimp","Emperor shrimp","crustacean","organisms","reef","detritus","It hitches rides on sea cucumbers and sea slugs, gaining transport and a meal of scraps.", kind="invert")
S("gast-turbansnail","Turban snail","mollusc (gastropod)","organisms","rocky","algae","It grazes algae on rocky shores and seals its shell with a thick, stony 'cat's eye' trapdoor.", kind="invert")
S("gast-topshell","Top shell","mollusc (gastropod)","organisms","rocky","algae","Cone-shaped and pearly within, it scrapes a living from the algae film on tidal rocks.", kind="invert")
S("gast-nerite","Nerite","mollusc (gastropod)","organisms","shore","algae","A small, tough, rounded snail, it endures the pounding intertidal zone while grazing algae from stone.", kind="invert")
S("gast-drupe","Drupe snail","mollusc (gastropod)","organisms","rocky","inverts","A predatory rock snail, it drills neat holes through the shells of barnacles and other prey to feed.", kind="invert")
S("gast-bubbleshell","Bubble shell","mollusc (gastropod)","organisms","sand","inverts","With only a thin, fragile shell, this snail glides over sand engulfing small prey whole.", kind="invert")
S("gast-tunshell","Tun shell","mollusc (gastropod)","organisms","sand","urchins","Carrying a large, thin, lightweight shell, this hunter can secrete acid to subdue urchins and sea cucumbers.", kind="invert")
S("cnid-mushroomcoral","Mushroom coral","cnidarian (stony coral)","organisms","reef","plankton","Unusually, it lives unattached on the seabed and can slowly move and right itself if flipped over.", kind="invert")
S("cnid-bubblecoral","Bubble coral","cnidarian (stony coral)","organisms","reef","plankton","By day it inflates grape-like bubbles, then extends stinging tentacles at night to feed.", kind="invert")
S("cnid-suncoral","Sun coral","cnidarian (cup coral)","organisms","reef","plankton","Brilliant orange and not reliant on algae, it opens its tentacles mainly at night to capture plankton.", kind="invert")
S("cnid-pillarcoral","Pillar coral","cnidarian (stony coral)","organisms","reef","plankton","It grows in tall finger-like columns and keeps its tentacles out even by day, giving it a furry look.", kind="invert")
S("cnid-carpetanemone","Carpet anemone","cnidarian (anemone)","organisms","reef","fish","A large, sticky anemone, it hosts clownfish and shrimp while stinging and engulfing prey that lands on it.", kind="invert")
S("cnid-magnificentanemone","Magnificent anemone","cnidarian (anemone)","organisms","reef","fish","One of the grandest host anemones, its colorful column shelters clown anemonefish among the tentacles.", kind="invert")
S("cnid-zoanthid","Zoanthid (button polyps)","cnidarian (zoanthid)","organisms","reef","plankton","These colonial polyps carpet reef rock in bright mats, and some contain one of the most potent natural toxins known.", kind="invert")
S("echi-cushionstar","Cushion star","echinoderm","organisms","reef","detritus","Thick and pentagon-shaped, this plump sea star creeps over the reef grazing on films and small organisms.", kind="invert")
S("echi-fireurchin","Fire urchin","echinoderm","organisms","reef","algae","Flamboyantly colored, its venom-tipped spines warn predators away, and tiny animals often shelter among them.", kind="invert")
S("echi-flowerurchin","Flower urchin","echinoderm","organisms","reef","algae","Covered in flower-like pincers that inject a painful venom, it is considered one of the most dangerous urchins.", kind="invert")
S("echi-hearturchin","Heart urchin (sea potato)","echinoderm","organisms","sand","detritus","Covered in fine fur-like spines, this heart-shaped urchin lives buried in sand, sifting out tiny food particles.", kind="invert")

# ---- apply scientific names (accuracy: exact taxon for prose + photo fetch) ----
try:
    from species_sci import SCI
    _known = set(s["id"] for s in g.SPECS)
    _bad = [k for k in SCI if k not in _known]
    if _bad:
        print("WARNING: SCI keys not matching a spec:", _bad)
    _missing = [s["id"] for s in g.SPECS if s["id"] not in SCI]
    if _missing:
        print("NOTE: specs with no SCI entry (%d):" % len(_missing), _missing[:10])
    _n = 0
    for _s in g.SPECS:
        if _s["id"] in SCI and SCI[_s["id"]]:
            _s["sci"] = SCI[_s["id"]]; _n += 1
    print("scientific names applied:", _n)
except Exception as _e:
    print("SCI not applied:", _e)

# ============================ BUILD UNITS & EMIT ============================
def idp(pfx):
    return [s["id"] for s in g.SPECS if s["id"].startswith(pfx)]

_pelagic = {"tuna-bluefin","tuna-yellowfin","mackerel","wahoo","kingmackerel","bonito","mahimahi","marlin-blue","sailfish","swordfish","bluefish","jackmackerel","opah","sunfish-mola","oarfish","herring","sardine","anchovy","menhaden","capelin","barracuda"}
_deep = {"anglerfish-deep","viperfish","dragonfish","gulper","hatchetfish","lanternfish","bristlemouth","fangtooth","tripod","grenadier","blobfish","coffinfish","lizardfish","snailfish-deep","cusk-eel","coelacanth","chimaera"}
_eels = {"moray","gardeneel","conger","electriceel","freshwater-eel","lamprey","hagfish","sturgeon","seadragon"}
_fish = idp("fish-")
def _stem(i): return i[len("fish-"):]
_reef = [i for i in _fish if _stem(i) not in _pelagic and _stem(i) not in _deep and _stem(i) not in _eels]
_pel  = [i for i in _fish if _stem(i) in _pelagic]
_dp   = [i for i in _fish if _stem(i) in _deep]
_el   = [i for i in _fish if _stem(i) in _eels]

g.chunk_units("Reef & Coastal Fishes","Colorful fish of reefs, shallows and shores","organisms","Core",_reef,6)
g.chunk_units("Open-Ocean Fishes","Fast swimmers of the blue water","organisms","Core",_pel,6)
g.chunk_units("Deep-Sea Fishes","Strange fish of the lightless depths","habitats","Advanced",_dp,6)
g.chunk_units("Eels & Unusual Fishes","Eels and other odd-bodied fishes","organisms","Core",_el,6)
g.chunk_units("Sharks","Cartilaginous hunters of every sea","organisms","Core",idp("shark-"),6)
g.chunk_units("Rays, Skates & Sawfish","Flattened relatives of the sharks","organisms","Core",idp("ray-"),6)
g.chunk_units("Marine Mammals","Whales, dolphins, seals and their kin","organisms","Core",idp("mammal-"),6)
g.chunk_units("Sea Turtles & Marine Reptiles","Air-breathing reptiles of the sea","organisms","Core",idp("reptile-"),6)
g.chunk_units("Seabirds","Birds that make a living from the ocean","organisms","Core",idp("bird-"),6)
g.chunk_units("Cnidarians","Jellyfish, corals, anemones and kin","organisms","Core",idp("cnid-"),6)
g.chunk_units("Cephalopods","Octopuses, squid, cuttlefish and nautilus","organisms","Core",idp("ceph-"),6)
g.chunk_units("Sea Snails & Slugs","Gastropods, from conchs to nudibranchs","organisms","Core",idp("gast-"),6)
g.chunk_units("Clams & Other Molluscs","Bivalves and chitons","organisms","Core",idp("biv-")+idp("moll-"),6)
g.chunk_units("Crustaceans","Crabs, shrimp, lobsters and kin","organisms","Core",idp("crus-"),6)
g.chunk_units("Echinoderms","Sea stars, urchins and sea cucumbers","organisms","Core",idp("echi-"),6)
g.chunk_units("Marine Worms","The many worms of the sea","organisms","Core",idp("worm-"),6)
g.chunk_units("Sponges & Tunicates","Simple filter feeders of reef and deep","organisms","Core",idp("spng-")+idp("tuni-"),6)
g.chunk_units("Plankton & Microbes","The tiny drifters that run the ocean","ecology","Core",idp("plank-")+idp("microbe-"),6)
g.chunk_units("Algae & Marine Plants","Seaweeds, seagrasses and mangroves","organisms","Core",idp("algae-")+idp("plant-"),6)

g.emit()

# ---- also emit a per-species query manifest for the photo pipeline ----
import json as _json
_q = {}
for _s in g.SPECS:
    _q[_s["id"]] = {"title": _s["name"], "q": (_s["sci"] if _s.get("sci") else _s["name"]), "group": _s["group"]}
with open("/home/claude/sea/species_queries.json", "w", encoding="utf-8") as _f:
    _json.dump(_q, _f, indent=0, ensure_ascii=False)
print("wrote species_queries.json entries:", len(_q))

# ---- per-species meta for guided Expedition challenges ----
_meta = {}
for _s in g.SPECS:
    _cat = g.simple_cat(_s["group"])
    _hab = g.HAB.get(_s["hab"], _s["hab"])
    _diet = g.DIET.get(_s["diet"], _s["diet"]) if _s["diet"] else ""
    _art = _s["art"] or g.art_for(_cat, _s["hab"])
    _meta[_s["id"]] = {"name": _s["name"], "cat": _cat, "group": _s["group"],
                       "hab": _hab, "habKey": _s["hab"], "diet": _diet,
                       "art": _art, "trait": _s["trait"]}
with open("/home/claude/sea/seahype-pathmeta.js", "w", encoding="utf-8") as _f:
    _f.write("window.__SEA_SPECIES_META__ = " + _json.dumps(_meta, ensure_ascii=False) + ";\n")
print("wrote species meta entries:", len(_meta))
