#!/usr/bin/env python3
"""
SeaHype photo embedder.

Takes the photos fetched by fetch_photos.py, optimizes them (resize + recompress)
and wires them into the app by writing seahype-photos.js. Then you rebuild the
single HTML with `node build_html.js`.

Requires Pillow:   pip install Pillow

Two modes:
  --mode folder  (DEFAULT, recommended)
      Writes optimized images to  dist_photos/photos/<id>.jpg  and sets the app
      to load them by relative path. Keeps the HTML small (~1.3 MB). Ship the
      HTML together with the photos/ folder beside it.
  --mode inline
      Base64-embeds every image directly into seahype-photos.js so the final
      HTML is ONE self-contained file. Simplest to share, but the HTML grows to
      ~15-30 MB depending on size/quality.

Examples:
    python3 embed_photos.py                      # folder mode, 640px, q78
    python3 embed_photos.py --mode inline        # single big HTML
    python3 embed_photos.py --max-dim 480 --quality 72   # smaller
"""
import json, os, base64, argparse
from io import BytesIO
try:
    from PIL import Image
except ImportError:
    raise SystemExit("Pillow is required:  pip install Pillow")

HERE = os.path.dirname(os.path.abspath(__file__))
PHOTODIR = os.path.join(HERE, "photos")
OUT_JS = os.path.join(HERE, "seahype-photos.js")

def optimize(path, max_dim, quality):
    im = Image.open(path)
    if im.mode not in ("RGB", "L"):
        im = im.convert("RGB")
    elif im.mode == "L":
        im = im.convert("RGB")
    w, h = im.size
    scale = min(1.0, float(max_dim) / float(max(w, h)))
    if scale < 1.0:
        im = im.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.LANCZOS)
    buf = BytesIO()
    im.save(buf, format="JPEG", quality=quality, optimize=True, progressive=True)
    return buf.getvalue()

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["folder", "inline"], default="folder")
    ap.add_argument("--max-dim", type=int, default=640)
    ap.add_argument("--quality", type=int, default=78)
    args = ap.parse_args()

    credits_path = os.path.join(PHOTODIR, "_credits.json")
    if not os.path.exists(credits_path):
        raise SystemExit("No photos/_credits.json found. Run fetch_photos.py first.")
    credits = json.load(open(credits_path, encoding="utf-8"))

    photos = {}
    total_bytes = 0
    out_folder = os.path.join(HERE, "dist_photos", "photos")
    if args.mode == "folder":
        os.makedirs(out_folder, exist_ok=True)

    kept = []
    for c in credits:
        lid = c["id"]
        src = os.path.join(PHOTODIR, lid + ".jpg")
        if not os.path.exists(src):
            continue
        try:
            data = optimize(src, args.max_dim, args.quality)
        except Exception as e:
            print("skip", lid, "-", e)
            continue
        total_bytes += len(data)
        kept.append(c)
        if args.mode == "inline":
            photos[lid] = "data:image/jpeg;base64," + base64.b64encode(data).decode("ascii")
        else:
            with open(os.path.join(out_folder, lid + ".jpg"), "wb") as f:
                f.write(data)
            photos[lid] = "photos/" + lid + ".jpg"

    # trim credits to the images we actually kept
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write("/* Generated by embed_photos.py — real species photographs. */\n")
        f.write("window.__SEA_PHOTOS__ = " + json.dumps(photos) + ";\n")
        f.write("window.__SEA_PHOTO_CREDITS__ = " + json.dumps(kept) + ";\n")

    print("images wired:", len(photos), "| mode:", args.mode,
          "| optimized payload: %.1f MB" % (total_bytes / 1048576.0))
    if args.mode == "folder":
        print("Optimized images written to:", out_folder)
        print("=> Rebuild:  node build_html.js")
        print("=> Then ship 'index.html' WITH the")
        print("   dist_photos/photos/ folder placed next to it (rename to photos/).")
    else:
        print("=> Rebuild:  node build_html.js   (HTML will be large but self-contained)")

if __name__ == "__main__":
    main()
